repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  -   id: trailing-whitespace
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.8
      args: [--line-length=79]

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: git://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
    - id: clang-format
      name: clang-format
      description: Format files with ClangFormat.
      entry: clang-format
      language: system
      files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|js|m|proto|vert)$
      args: ['-fallback-style=none', '-i', '-style=google']
